dist: trusty
language: java
node_js: 12
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
services:
  - docker
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  npm: true
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - gradle/wrapper/
jobs:
  include:
    - stage: e2e
      script: source e2e.sh
      if: branch = e2e
install:
  - true  #If install is not set, travis will run gradle assemble
script: /bin/sh travis/build.sh
deploy:
  - provider: script
    skip_cleanup: true
    script: /bin/sh travis/uploadArchives.sh
    on:
      branch: main
      jdk: oraclejdk8
  - provider: script
    skip_cleanup: true
    script: /bin/sh travis/release.sh
    on:
      branch: $RELEASE_BRANCH
      jdk: oraclejdk8
#  - provider: script
#    skip_cleanup: true
#    script: /bin/sh travis/sonarqube.sh
#    on:
#      branch: main
#      jdk: oraclejdk9
before_install:
  - |
    if [ -z "${signingKeyId}" ]; then
      echo "No signing the artifacts"
    else
      echo "Signing artifacts"
      openssl aes-256-cbc -K $encrypted_98cf1ffdea51_key -iv $encrypted_98cf1ffdea51_iv -in travis/symbol-sdk-java.gpg.enc -out symbol-sdk-java.gpg -d
    fi
